<html>
	<head>
	</head>
	<body>

	<?php
			$url = "http://picasaweb.google.com/data/feed/base/user/107401320610499259896/albumid/6065229773950541889?alt=rss&kind=photo&authkey=Gv1sRgCNak7e60l-7VlgE&hl=fr";
			$xml = simplexml_load_file($url);
			$i=2;
			echo "<table>";			
			foreach ($xml->channel->item as $photo){
				if ($i%2 == 0) echo "<tr>";
				
				echo "<td><img width='400px' src='".$photo->enclosure["url"]."'/><br/><p align='center'>".$photo->title."</p></td>";
				
				if($i++ == 0) echo"</tr>";				
			}
			echo "</table>";
			?>
	</body>

</html>