<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />

	</head>
	
	<body>
		<?php
//charge le flux rss dans un objet PHP
$xml = simplexml_load_file('https://picasaweb.google.com/data/feed/base/user/107401320610499259896/albumid/6065229773950541889?alt=rss&kind=photo&authkey=Gv1sRgCNak7e60l-7VlgE&hl=fr');
echo "<h1 align='center' style='color:cyan' > Etudiants M2 THYP 14/15</h1>";
foreach ($xml->channel->item as $tof) {

	echo "<div align='center'><img src='".$tof->enclosure["url"]."' />" . "<p style='color:Red'>$tof->title</p></div>"; 

}
?>
	</body>
</html>